import { Inter } from "next/font/google";
import SessionAuthProvider from "@/src/context/SessionAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <main lang="en">
        {children}
    </main>
  );
}
